app/portal/forms.py
from flask_wtf import FlaskForm
from app.models import User, Department, Faculty
from wtforms import StringField, TextAreaField, SelectField, IntegerField, DateField, PasswordField, SubmitField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired, Length, ValidationError, Email, EqualTo
from wtforms_sqlalchemy.fields import QuerySelectField

def department_query():
	return Department.query

def faculty_query():
	return Faculty.query

class MakeStudentForm(FlaskForm):
	firstname = StringField('',
		validators=[DataRequired('Please fill in your firstname')])
	lastname = StringField('',
		validators=[DataRequired('Please fill in your lastname')])
	middlename = StringField('')
	department = QuerySelectField(query_factory=department_query, allow_blank=True, get_label='name')
	regnumber = StringField('', validators=[DataRequired('Please fill in registration number')])
	level = SelectField('', choices=[('',''),('100','100'),('200','200'),('300','300'),('400','400'),('500','500')])
	email = StringField('', validators=[DataRequired('Please fill in a valid Email')])
	phone = IntegerField('', validators=[DataRequired('Please fill in your phone number')])
	image = FileField('', validators=[FileAllowed(['jpg','png', 'jpeg','JPG','JPEG','PNG'])])

	def __init__(self, *args, **kwargs):
		kwargs['csrf_enabled'] = False
		super(MakeStudentForm, self).__init__(*args, **kwargs)

	def validate_regnumber(self, regnumber):
		user = User.query.filter_by(regnumber=regnumber.data).first()
		if user:
			raise ValidationError('Reg number already exists!')

class RegisterStudentCourse(FlaskForm):
	regnumber = IntegerField('',
		validators=[DataRequired('Please fill in a reg number')])

	def __init__(self, *args, **kwargs):
		kwargs['csrf_enabled'] = False
		super(RegisterStudentCourse, self).__init__(*args, **kwargs)

class MakeFacultyForm(FlaskForm):
	name = StringField('',
		validators=[DataRequired('Please fill in the faculty name')])

	def __init__(self, *args, **kwargs):
		kwargs['csrf_enabled'] = False
		super(MakeFacultyForm, self).__init__(*args, **kwargs)

	def validate_faculty(self, faculty):
		faculty = Faculty.query.filter_by(faculty=name.data).first()
		if faculty:
			raise ValidationError('Faculty already exists!')

class MakeDepartmentForm(FlaskForm):
	name = StringField('',
		validators=[DataRequired('Please fill in the faculty name')])
	faculty = QuerySelectField(query_factory=faculty_query, allow_blank=True, get_label='name', validators=[DataRequired('Please select a faculty')])

	def __init__(self, *args, **kwargs):
		kwargs['csrf_enabled'] = False
		super(MakeDepartmentForm, self).__init__(*args, **kwargs)

	def validate_department(self, department):
		department = Department.query.filter_by(department=name.data).first()
		if department:
			raise ValidationError('Department already exists!')

class MakeCourseForm(FlaskForm):
	name = StringField('',
		validators=[DataRequired('Please fill in the course name')])
	department = QuerySelectField(query_factory=department_query, allow_blank=True, get_label='name', validators=[DataRequired('Please select a department')])
	title = StringField('',
		validators=[DataRequired('Please fill in the course initial')])

	def __init__(self, *args, **kwargs):
		kwargs['csrf_enabled'] = False
		super(MakeCourseForm, self).__init__(*args, **kwargs)

	def validate_course(self, course):
		course = User.query.filter_by(course=name.data).first()
		if course:
			raise ValidationError('Course already exists!')
class EditStudentCourses(FlaskForm):
	
	picture = FileField('Update Student Photo',validators=[FileAllowed(["png","jpg"])])
	submit  = SubmitField('Update')

app/portal/__init__.py
from flask import Blueprint

portal = Blueprint('portal', __name__)

from . import views, forms

app/portal/views.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required,current_user
from ihufied import db
from . import portal
from app.utils import save_picture, update_picture, insert_picture
from passlib.hash import sha256_crypt as sha256
from app.models import User, Faculty, Department, Course
from app.portal.forms import MakeFacultyForm, MakeDepartmentForm, MakeCourseForm, MakeStudentForm, RegisterStudentCourse,EditStudentCourses

###################
#### ALL-VIEWS ####
###################

@portal.route('/register_student', methods=['GET','POST'])
@login_required
def register_student():
	form = MakeStudentForm()
	if form.validate_on_submit() and form.image.data:
		hashed_password = sha256.encrypt(str(form.firstname.data))		
		try:
			picture_name = save_picture(form.image.data)
			print('saved picture')
			student = User(firstname=form.firstname.data,lastname=form.lastname.data,middlename=form.middlename.data,department_id=str(form.department.data),regnumber=form.regnumber.data,email=form.email.data,phone=form.phone.data,level=form.level.data,password=hashed_password,image_name=picture_name[0],image=picture_name[1])
			print('saved')
			db.session.add(student)
			db.session.commit()
			flash('Student registered successfully.', 'success')
			return redirect(url_for('portal.register_student_courses'))
		except Exception as e:
			#delete_picture(form.image.data)
			flash(str(e), 'warning')
		return redirect(url_for('portal.register_student'))
	return render_template('/portal/register_student.html', form=form)

@portal.route('/register_student_courses', methods=['GET','POST'])
@login_required
def register_student_courses():
	form = RegisterStudentCourse()
	if form.validate_on_submit():
		try:
			student = User.query.filter_by(regnumber=form.regnumber.data).first()
			if student:
				courses = student.department.course_ids
				return render_template('/portal/register_student_courses.html', form=form, courses=courses,student_number=student)
			else:
				flash('Reg number does not exist!', 'warning')
				return redirect(url_for('portal.register_student_courses'))
		except Exception as e:
			flash(str(e), 'warning')
			return redirect(url_for('portal.register_student_courses'))
	return render_template('/portal/register_student_courses.html', form=form, courses=[], student_number='')

@portal.route('/remote_monitoring')
@login_required
def remote_monitoring():
    return render_template('/portal/monitoring.html')

@portal.route('/registered_students', methods= ['GET','POST'])
@login_required
def registered_students():
	page = request.args.get('page', 1 , type=int)
	student= User.query.order_by(User.lastname.asc()).paginate(page=page, per_page=25)
	pupils = User.query.order_by(User.lastname.asc())
	for i in pupils:
    		insert_picture(i.image,i.image_name)
	if request.method == 'POST':
		if request.form['detail']:
				the_student= request.form['detail']
				student= User.query.filter_by(id=the_student)	
				return render_template ('/portal/student_details.html',student=student)
	
	else:
		return render_template('/portal/registered_students.html',student =student)

@portal.route('/edit_courses/<student_reg>', methods =['POST','GET'])
@login_required
def edit_courses(student_reg):
	student= User.query.filter_by(regnumber=student_reg).first()
	current=url_for('static', filename='images/' + student.image_name)
	courses=student.department.course_ids #this line gets all the courses for department of this particular student
	form=EditStudentCourses()
	return render_template ('/portal/edit_courses.html',student=student,form=form,current=current,courses=courses)	

@portal.route('/modify_dept')
@login_required  
def modify_dept():
	makefacultyform = MakeFacultyForm()
	makedepartmentform = MakeDepartmentForm()
	makecourseform = MakeCourseForm()
	return render_template('/portal/modify_dept.html',makefacultyform=makefacultyform,makedepartmentform=makedepartmentform,makecourseform=makecourseform)

@portal.route('/create_faculty', methods=['POST'])
@login_required
def create_faculty():
	form = MakeFacultyForm()
	try:
		if form.validate_on_submit():
			faculty = Faculty(name=form.name.data)
			db.session.add(faculty)
			db.session.commit()
			flash('Faculty created!', 'success')
			return redirect(url_for('portal.modify_dept'))
		else:
			flash('Please fill in the form correctly!', 'warning')
			return redirect(url_for('portal.modify_dept'))
	except Exception as e:
		flash('{}'.format(e), 'warning')
		return redirect(url_for('portal.modify_dept'))

@portal.route('/create_department', methods=['POST'])
@login_required
def create_department():
	form = MakeDepartmentForm()
	try:
		if form.validate_on_submit():
			department = Department(name=form.name.data,faculty_id=str(form.faculty.data))
			db.session.add(department)
			db.session.commit()
			flash('Department created!', 'success')
			return redirect(url_for('portal.modify_dept'))
		else:
			flash('Please fill in the form correctly!', 'warning')
			return redirect(url_for('portal.modify_dept'))
	except Exception as e:
		flash('{}'.format(e), 'warning')
		return redirect(url_for('portal.modify_dept'))

@portal.route('/create_course', methods=['POST'])
@login_required
def create_course():
	form = MakeCourseForm()
	try:
		if form.validate_on_submit():
			course = Course(name=form.name.data,department_id=str(form.department.data),title=form.title.data)
			db.session.add(course)
			db.session.commit()
			flash('Course created successfully.', 'success')
			return redirect(url_for('portal.modify_dept'))
		else:
			flash('Please fill in the form correctly!', 'warning')
			return redirect(url_for('portal.modify_dept'))
	except Exception as e:
		flash('{}'.format(e), 'warning')
		return redirect(url_for('portal.modify_dept'))

@portal.route('/submit_registered_courses/<string:student_number>', methods=['POST'])
@login_required
def submit_registered_courses(student_number):
	try:
		student = User.query.filter_by(regnumber=student_number).first()
		form=EditStudentCourses()
		if form.picture.data:
			new_photo=update_picture(form.picture.data)
			student.image_name=new_photo
		print('1: {}'.format(student.course_subscription))
		del student.course_subscription
		print('2: {}'.format(student.course_subscription))
		for title in request.form.getlist('course_select'):
			get_course = Course.query.filter_by(title=title).first()
			get_course.course_subscribers.append(student)
		print('3: {}'.format(student.course_subscription))
		db.session.commit()
		flash('Courses registered successfully!', 'success')
		return redirect(url_for('portal.registered_students'))
	except Exception as e:
		flash(str(e), 'warning')
		return redirect(url_for('portal.register_student_courses'))

app/templates/base.html
{%extends 'bootstrap/base.html'%}
{%block head %}
{{super()}}
<link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}" type="image/x-icon"/>
<link rel="icon" href="{{url_for('static', filename='favicon.ico')}}" type="image/x-icon"/>
{%endblock%}
{%block title%}Ihufied{%endblock title%}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
{%endblock styles%}

{% block navbar %}
<div class="navbar navbar-inverse " role="navigation" style="border-radius:0px">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{url_for('main.index')}}" >Ihufied</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{url_for('main.index')}}">Home <i class="fas fa-home"></i></a></li>
                <li><a href="{{url_for('portal.register_student')}}">Portal <i class="fab fa-battle-net"></i></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('auth.change_password')}}">Change Password</a></li>
                        <li><a href="{{url_for('auth.change_email_request')}}">Change Email</a></li>
                        <li><a href="{{url_for('auth.signout')}}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{url_for('auth.signup')}}">Register <i class="far fa-user"></i></a></li>
                <li><a href="{{url_for('auth.signin')}}">Log In <i class="fas fa-sign-in-alt"></i></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}
{%block content%}
    <div class="container">
        {%for message in get_flashed_messages()%}
        <div class="alert alert-danger" role="alert" style="width: 64%; margin: 0 auto;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{message}}
        </div>
        {%endfor%}
    </div>
    {%block page_content%}{%endblock%}
{%endblock%}
{%block scripts%}
{{super()}}
<script src="https://kit.fontawesome.com/21fa939ee3.js" crossorigin="anonymous"></script>
{{moment.include_moment()}}
{%endblock%}

app/templates/index.html
{% extends 'base.html'%}

{%block page_content %}
<div class="container">
   <div class="card ">
        <h4 class="card-title">Our Vision</h4>
        <h6 class="card-subtitle mb-2 text-muted">...mitigating examination impersonation with trailing facial recognition technologies</h6>
        <img class="card-img-top img-responsive"  src="{{url_for('static', filename='landing.png')}}" alt="Facial recognition image"/>
        <div class="card-body">
        <p class="card-text">Ihufied is aimed to equip Universities with trialling facial recognition technologies to crack down on students who pay impersonators to sit for their exams. Our technology creates biometric profiles of students and then matches this with photos taken during exams. Our technology has over 90% accuracy, enjoy our portal.</p>
    </div>

    <div>
        <h6 class="card-subtitle mb-1 text-muted">Current session info: Checked in {{moment(current_time).format('LLLL')}}. That was {{moment(current_time).fromNow(refresh=True)}}</h6>
    </div>
    </div> 
</div>
{%endblock%}

app/templates/portal.html
<!DOCTYPE html>
<html lang="en">
{%block head%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block title%}<title>Ihufied | Portal</title>{%endblock%}

    <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}" type="image/x-icon"/>
    <link rel="icon" href="{{url_for('static', filename='favicon.ico')}}" type="image/x-icon"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&display=swap" rel="stylesheet">
    {%block link%}{%endblock%}
</head>
{%endblock%}
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler sideMenuToggler" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        <a class="navbar-brand" href="{{url_for('main.index')}}">Ihufied</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{url_for('auth.change_password')}}">Change Password</a>
                <a class="dropdown-item" href="{{url_for('auth.change_email_request')}}">Change Email</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{url_for('auth.signout')}}">Log Out</a>
              </div>
            </li>
            
          </ul>
          
        </div>
      </nav>

      <div class="wrapper d-flex">
            <div class="sideMenu bg-mattBlackLight">
                <div class="sidebar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{{url_for('portal.register_student')}}" class="nav-link px-2"><i class="fas fa-user-graduate icon"></i> <span class="text">Register Student</span></a>
                        </li>
                        <li class="nav-item">
                            <a href="{{url_for('portal.remote_monitoring')}}" class="nav-link px-2"><i class="fas fa-tv icon"></i> <span class="text">Remote Monitoring</span></a>
                        </li>
                        <li class="nav-item">
                            <a href="{{url_for('portal.registered_students')}}" class="nav-link px-2"><i class="far fa-registered icon"></i> <span class="text"> Registered Students</span></a>
                        </li>
                        <li class="nav-item">
                            <a href="{{url_for('portal.modify_dept')}}" class="nav-link px-2"><i class="far fa-plus-square icon"></i> <span class="text">Create/Delete Dept.</span></a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="sideMenuToggler nav-link px-2"><i class="fas fa-compress icon"></i> <span class="text">Resize</span></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="content container margin_top">
              {% include 'includes/_messages.html' %}
              {%block page_content%}
                 <div class="bg-mattBlackLight p-3">
                    <h4 class="mb-2">New Clients</h4>
                 </div>
              {%endblock%} 
            </div>
      </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/21fa939ee3.js" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='js/script.js')}}" crossorigin="anonymous"></script>
</body>
</html>