app/portal/forms.py
from flask_wtf import FlaskForm
from app.models import User, Department, Faculty
from wtforms import StringField, TextAreaField, SelectField, IntegerField, DateField, PasswordField, SubmitField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired, Length, ValidationError, Email, EqualTo
from wtforms_sqlalchemy.fields import QuerySelectField

def department_query():
	return Department.query

def faculty_query():
	return Faculty.query

class MakeStudentForm(FlaskForm):
	firstname = StringField('',
		validators=[DataRequired('Please fill in your firstname')])
	lastname = StringField('',
		validators=[DataRequired('Please fill in your lastname')])
	middlename = StringField('')
	department = QuerySelectField(query_factory=department_query, allow_blank=True, get_label='name')
	regnumber = StringField('', validators=[DataRequired('Please fill in registration number')])
	level = SelectField('', choices=[('',''),('100','100'),('200','200'),('300','300'),('400','400'),('500','500')])
	email = StringField('', validators=[DataRequired('Please fill in a valid Email')])
	phone = IntegerField('', validators=[DataRequired('Please fill in your phone number')])
	image = FileField('', validators=[FileAllowed(['jpg','png', 'jpeg','JPG','JPEG','PNG'])])

	def __init__(self, *args, **kwargs):
		kwargs['csrf_enabled'] = False
		super(MakeStudentForm, self).__init__(*args, **kwargs)

	def validate_regnumber(self, regnumber):
		user = User.query.filter_by(regnumber=regnumber.data).first()
		if user:
			raise ValidationError('Reg number already exists!')

class RegisterStudentCourse(FlaskForm):
	regnumber = IntegerField('',
		validators=[DataRequired('Please fill in a reg number')])

	def __init__(self, *args, **kwargs):
		kwargs['csrf_enabled'] = False
		super(RegisterStudentCourse, self).__init__(*args, **kwargs)

class MakeFacultyForm(FlaskForm):
	name = StringField('',
		validators=[DataRequired('Please fill in the faculty name')])

	def __init__(self, *args, **kwargs):
		kwargs['csrf_enabled'] = False
		super(MakeFacultyForm, self).__init__(*args, **kwargs)

	def validate_faculty(self, faculty):
		faculty = Faculty.query.filter_by(faculty=name.data).first()
		if faculty:
			raise ValidationError('Faculty already exists!')

class MakeDepartmentForm(FlaskForm):
	name = StringField('',
		validators=[DataRequired('Please fill in the faculty name')])
	faculty = QuerySelectField(query_factory=faculty_query, allow_blank=True, get_label='name', validators=[DataRequired('Please select a faculty')])

	def __init__(self, *args, **kwargs):
		kwargs['csrf_enabled'] = False
		super(MakeDepartmentForm, self).__init__(*args, **kwargs)

	def validate_department(self, department):
		department = Department.query.filter_by(department=name.data).first()
		if department:
			raise ValidationError('Department already exists!')

class MakeCourseForm(FlaskForm):
	name = StringField('',
		validators=[DataRequired('Please fill in the course name')])
	department = QuerySelectField(query_factory=department_query, allow_blank=True, get_label='name', validators=[DataRequired('Please select a department')])
	title = StringField('',
		validators=[DataRequired('Please fill in the course initial')])

	def __init__(self, *args, **kwargs):
		kwargs['csrf_enabled'] = False
		super(MakeCourseForm, self).__init__(*args, **kwargs)

	def validate_course(self, course):
		course = User.query.filter_by(course=name.data).first()
		if course:
			raise ValidationError('Course already exists!')
class EditStudentCourses(FlaskForm):
	
	picture = FileField('Update Student Photo',validators=[FileAllowed(["png","jpg"])])
	submit  = SubmitField('Update')

app/portal/__init__.py
from flask import Blueprint

portal = Blueprint('portal', __name__)

from . import views, forms

app/portal/views.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required,current_user
from ihufied import db
from . import portal
from app.utils import save_picture, update_picture, insert_picture
from passlib.hash import sha256_crypt as sha256
from app.models import User, Faculty, Department, Course
from app.portal.forms import MakeFacultyForm, MakeDepartmentForm, MakeCourseForm, MakeStudentForm, RegisterStudentCourse,EditStudentCourses

###################
#### ALL-VIEWS ####
###################

@portal.route('/register_student', methods=['GET','POST'])
@login_required
def register_student():
	form = MakeStudentForm()
	if form.validate_on_submit() and form.image.data:
		hashed_password = sha256.encrypt(str(form.firstname.data))		
		try:
			picture_name = save_picture(form.image.data)
			print('saved picture')
			student = User(firstname=form.firstname.data,lastname=form.lastname.data,middlename=form.middlename.data,department_id=str(form.department.data),regnumber=form.regnumber.data,email=form.email.data,phone=form.phone.data,level=form.level.data,password=hashed_password,image_name=picture_name[0],image=picture_name[1])
			print('saved')
			db.session.add(student)
			db.session.commit()
			flash('Student registered successfully.', 'success')
			return redirect(url_for('portal.register_student_courses'))
		except Exception as e:
			#delete_picture(form.image.data)
			flash(str(e), 'warning')
		return redirect(url_for('portal.register_student'))
	return render_template('/portal/register_student.html', form=form)

@portal.route('/register_student_courses', methods=['GET','POST'])
@login_required
def register_student_courses():
	form = RegisterStudentCourse()
	if form.validate_on_submit():
		try:
			student = User.query.filter_by(regnumber=form.regnumber.data).first()
			if student:
				courses = student.department.course_ids
				return render_template('/portal/register_student_courses.html', form=form, courses=courses,student_number=student)
			else:
				flash('Reg number does not exist!', 'warning')
				return redirect(url_for('portal.register_student_courses'))
		except Exception as e:
			flash(str(e), 'warning')
			return redirect(url_for('portal.register_student_courses'))
	return render_template('/portal/register_student_courses.html', form=form, courses=[], student_number='')

@portal.route('/remote_monitoring')
@login_required
def remote_monitoring():
    return render_template('/portal/monitoring.html')

@portal.route('/registered_students', methods= ['GET','POST'])
@login_required
def registered_students():
	page = request.args.get('page', 1 , type=int)
	student= User.query.order_by(User.lastname.asc()).paginate(page=page, per_page=25)
	pupils = User.query.order_by(User.lastname.asc())
	for i in pupils:
    		insert_picture(i.image,i.image_name)
	if request.method == 'POST':
		if request.form['detail']:
				the_student= request.form['detail']
				student= User.query.filter_by(id=the_student)	
				return render_template ('/portal/student_details.html',student=student)
	
	else:
		return render_template('/portal/registered_students.html',student =student)

@portal.route('/edit_courses/<student_reg>', methods =['POST','GET'])
@login_required
def edit_courses(student_reg):
	student= User.query.filter_by(regnumber=student_reg).first()
	current=url_for('static', filename='images/' + student.image_name)
	courses=student.department.course_ids #this line gets all the courses for department of this particular student
	form=EditStudentCourses()
	return render_template ('/portal/edit_courses.html',student=student,form=form,current=current,courses=courses)	

@portal.route('/modify_dept')
@login_required  
def modify_dept():
	makefacultyform = MakeFacultyForm()
	makedepartmentform = MakeDepartmentForm()
	makecourseform = MakeCourseForm()
	return render_template('/portal/modify_dept.html',makefacultyform=makefacultyform,makedepartmentform=makedepartmentform,makecourseform=makecourseform)

@portal.route('/create_faculty', methods=['POST'])
@login_required
def create_faculty():
	form = MakeFacultyForm()
	try:
		if form.validate_on_submit():
			faculty = Faculty(name=form.name.data)
			db.session.add(faculty)
			db.session.commit()
			flash('Faculty created!', 'success')
			return redirect(url_for('portal.modify_dept'))
		else:
			flash('Please fill in the form correctly!', 'warning')
			return redirect(url_for('portal.modify_dept'))
	except Exception as e:
		flash('{}'.format(e), 'warning')
		return redirect(url_for('portal.modify_dept'))

@portal.route('/create_department', methods=['POST'])
@login_required
def create_department():
	form = MakeDepartmentForm()
	try:
		if form.validate_on_submit():
			department = Department(name=form.name.data,faculty_id=str(form.faculty.data))
			db.session.add(department)
			db.session.commit()
			flash('Department created!', 'success')
			return redirect(url_for('portal.modify_dept'))
		else:
			flash('Please fill in the form correctly!', 'warning')
			return redirect(url_for('portal.modify_dept'))
	except Exception as e:
		flash('{}'.format(e), 'warning')
		return redirect(url_for('portal.modify_dept'))

@portal.route('/create_course', methods=['POST'])
@login_required
def create_course():
	form = MakeCourseForm()
	try:
		if form.validate_on_submit():
			course = Course(name=form.name.data,department_id=str(form.department.data),title=form.title.data)
			db.session.add(course)
			db.session.commit()
			flash('Course created successfully.', 'success')
			return redirect(url_for('portal.modify_dept'))
		else:
			flash('Please fill in the form correctly!', 'warning')
			return redirect(url_for('portal.modify_dept'))
	except Exception as e:
		flash('{}'.format(e), 'warning')
		return redirect(url_for('portal.modify_dept'))

@portal.route('/submit_registered_courses/<string:student_number>', methods=['POST'])
@login_required
def submit_registered_courses(student_number):
	try:
		student = User.query.filter_by(regnumber=student_number).first()
		form=EditStudentCourses()
		if form.picture.data:
			new_photo=update_picture(form.picture.data)
			student.image_name=new_photo
		print('1: {}'.format(student.course_subscription))
		del student.course_subscription
		print('2: {}'.format(student.course_subscription))
		for title in request.form.getlist('course_select'):
			get_course = Course.query.filter_by(title=title).first()
			get_course.course_subscribers.append(student)
		print('3: {}'.format(student.course_subscription))
		db.session.commit()
		flash('Courses registered successfully!', 'success')
		return redirect(url_for('portal.registered_students'))
	except Exception as e:
		flash(str(e), 'warning')
		return redirect(url_for('portal.register_student_courses'))

app/templates/portal/edit_courses.html
{%extends 'portal.html'%}
{%block page_content%}
   
<form action="{{url_for('portal.submit_registered_courses', student_number=student.regnumber)}}" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="bg-mattBlackLight p-1">
        <h1 class="mb-1">
            {{student.lastname}} {{student.middlename}} {{student.firstname}}
            <span style="float:right; margin-right:10px;"> </span>
         </h1>       
    </div>

    <div class="container">
        <div class="row">
            
                <div class="col-sm-4 mt-5">
                    <img style="max-width: 100%; height: auto; " class="pt-1" src="{{current}}" alt="" srcset="">
                </div>

                <div class="col-sm-6">
                    <h1 class="mb-4"> Select Courses</h1>
                   
                        {% for course in courses%}
                        <div class="ml-4">
                            {%if course in student.course_subscription%}
                            <input type="checkbox" checked="true" class="form-check-input" name="course_select" value="{{course.title}}" id="">{{course.name}} ({{course.title}})
                            {%else%}
                            <input type="checkbox" name="course_select"  class="form-check-input"  value="{{ course.title }}" id="">{{course.name}} ({{course.title}})
                            {%endif%}
                        </div>

                       
                    {%endfor%}
                </div>
        </div>

        <div class="row">
         
                <div class="col-sm-3">
                 
                   
                        <div class="form-group pt-2" >
                            {{form.picture.label()}}
                            {{form.picture(class="form-control-file border")}}
                        </div>
                
                </div>
            
        </div>
                    
          
        
    </div>
    <div>
        {{form.submit(class='btn btn-primary')}}
    </div>
</form>
{%endblock page_content%}

app/templates/portal/modify_dept.html
{% extends 'portal.html' %}

{%block page_content%}
     <div class="bg-mattBlackLight p-3 mb-4">
        <h4 class="mb-2">Create Course/Department/Faculty</h4>
     </div>
	<div class="mt-4">
		<h4>Create Course</h4><hr style="background-color: #fff;">
	     <form action="{{url_for('portal.create_course')}}" method="POST">
     	{% from 'includes/_formhelpers.html' import render_field %}
	     	{{ makecourseform.hidden_tag() }}
		  <div class="form-group">
		  	<div class="row">
		  	<div class="col-md-4">
			    <label for="coursename">Course name</label>
			    {{render_field(makecourseform.name, class_='form-control', id='coursename', required='true')}}
			</div>
			<div class="col-md-4">
			    <label for="coursetitle">Course Title</label>
			    {{render_field(makecourseform.title, class_='form-control', id='coursetitle', required='true')}}
			</div>
			<div class='col-md-4'>
				<label for="relateddepartment"></label>
		    	{{render_field(makecourseform.department, class_='form-control', id='relateddepartment', required='true')}}
			</div>
		</div>
		  </div>
		  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
	<div class="mt-4">
		<h4>Create Department</h4><hr style="background-color: #fff;">
	     <form action="{{url_for('portal.create_department')}}" method="POST">
	     	{{ makedepartmentform.hidden_tag() }}
		  <div class="form-group">
		  	<div class="row">
		  	<div class="col-md-6">
			    <label for="departmentname">Department name</label>
			    {{render_field(makedepartmentform.name, class_='form-control', id='departmentname', required='true')}}
			</div>
			<div class='col-md-6'>
				<label for="relatedfaculty"></label>
		    	{{render_field(makedepartmentform.faculty, class_='form-control', id='relatedfaculty', required='true')}}
			</div>
		</div>
		  </div>
		  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
	<div class="mt-4">
     <h4>Create Faculty</h4><hr style="background-color: #fff;">
     <form action="{{url_for('portal.create_faculty')}}" method="POST">
     	{{ makefacultyform.hidden_tag() }}
	  <div class="form-group">
	    <label for="facultyname">Faculty name</label>
	    {{render_field(makefacultyform.name, class_='form-control', id='facultyname', required='true')}}
	  </div>
	  <button type="submit" class="btn btn-primary">Submit</button>
	</form>
</div>
{%endblock%} 

app/templates/portal/monitoring.html
{% extends 'portal.html' %}

{%block page_content%}
     <div class="bg-mattBlackLight p-3">
        <h4 class="mb-2">Remote Monitoring</h4>
     </div>
{%endblock%}

app/templates/portal/register_student.html
{% extends 'portal.html' %}

{%block page_content%}
     <div class="bg-mattBlackLight p-3">
        <h4 class="mb-2">Register student</h4>
     </div>
     <div class="mt-4">
        <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {% from 'includes/_formhelpers.html' import render_field %}
        <div class="row">
	        <div class="col-sm-6 mb-3">
	            <div class="floating-label">
	              <label for="floatingregnumber">Reg number</label>
	              {{render_field(form.regnumber, class_='form-control', placeholder='Reg number', id='floatingregnumber', type='number')}}
	            </div>
	        </div>
	        <div class="col-sm-6 mb-3">
	            <div class="floating-label">
	              <label for="floatingemail">Email</label>
	              {{render_field(form.email, class_='form-control', placeholder='Email', id='floatingemail')}}
	            </div>
	        </div>
        </div>
        <div class="row">
	        <div class="col-sm-6 mb-3">
	        	<div class="floating-label">
	              <label for="floatingdepartment"></label>
	              {{render_field(form.department, class_='custom-select form-control', placeholder='Department', id='floatingdepartment')}}
	            </div>
	        </div>
	         <div class="col-sm-6 mb-3">
	            <div class="floating-label">
	              <label for="floatingfirstname">Level</label>
	              {{render_field(form.level, class_='form-control custom-select', placeholder='Level', id='floatinglevel')}}
	            </div>
	        </div>
        </div>
        <div class="row">
	        <div class="col-sm-6 mb-3">
	            <div class="floating-label">
	              <label for="floatingfirstname">First name</label>
	              {{render_field(form.firstname, class_='form-control', placeholder='First name', id='floatingfirstname')}}
	            </div>
	        </div>
	         <div class="col-sm-6 mb-3">
	            <div class="floating-label">
	              <label for="floatinglastname">Last name</label>
	              {{render_field(form.lastname, class_='form-control', placeholder='Last name', id='floatinglastname')}}
	            </div>
	        </div>
        </div>
        <div class="row">
	        <div class="col-sm-6 mb-3">
	            <div class="floating-label">
	              <label for="floatingmiddlename">Middle name</label>
	              {{render_field(form.middlename, class_='form-control', placeholder='Middle name', id='floatingmiddlename')}}
	            </div>
	        </div>
	         <div class="col-sm-6 mb-3">
	            <div class="floating-label">
	              <label for="floatingphone">Phone number</label>
	              {{render_field(form.phone, class_='form-control', placeholder='Phone number', id='floatingphone')}}
	            </div>
	        </div>
        </div>
        <div class="row">
        	<div class="col-sm-12 mb-3">
	        <div class="custom-file">
        		<label for="floatingemail">Student Image</label>
	        	{{render_field(form.image, class_='form-control-file border', placeholder='Image', id='customFile')}}
	        </div>
	    </div>
    	</div>
        <button type="submit" class="btn btn-primary btn-block col-sm-2">Submit</button>
    </form>
</div>
{%endblock%}

app/templates/portal/register_student_courses.html
{% extends 'portal.html' %}

{%block page_content%}
     <div class="bg-mattBlackLight p-3">
        <h4 class="mb-2">Register student courses</h4>
     </div>
     <div class="mt-4">
	     <form method="POST">
	     	{% from 'includes/_formhelpers.html' import render_field %}
	     	{{ form.hidden_tag() }}
		  <div class="form-group">
		    <label for="regnumber">Reg number</label>
		    {{render_field(form.regnumber, class_='form-control col-md-4', id='regnumber', required='true')}}
		  </div>
		  <button type="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
	{% if courses != []    %} 
	<div class="mt-4">
		<h4 class="mb-2">Select courses</h4>
		<form method="POST" action="{{url_for('portal.submit_registered_courses', student_number=student_number.regnumber)}}">
			{% for course in courses %}
			 	<div class="form-check-inline">
				  <label class="form-check-label">
						{% if course in student_number.course_subscription %}
						<input type="checkbox" checked="true" class="form-check-input" name="course_select" value="{{course.title}}">{{course.name}}({{course.title}})
						{% else %}
						<input type="checkbox" class="form-check-input" name="course_select" value="{{course.title}}">{{course.name}}({{course.title}})
						{% endif %}
				  </label>
				</div>
			{% endfor %}
		  <div class="row">
			  <div class="col-12">
			  	<button type="submit" class="btn btn-primary mt-2">Submit</button>
			  </div>
		  </div>
		</form> 
		<div class="mt-4">
			{% for course in student_number.course_subscription %}
				<p>{{course.name}} <i class="fas fa-check-circle"></i></p>
			{% endfor %}
		</div>
	</div>
	{% endif %}
{%endblock%}

app/templates/portal/registered_students.html
{% extends 'portal.html' %}

{%block page_content%}
     <div class="bg-mattBlackLight p-3">
        <h4 class="mb-2">Registered Students</h4>
     </div>
     <table style="width: 100%;">
       <tr style="height:50px; border-bottom: 5px solid rgb(41, 40, 40)">
            <th>Photo id</th>
            <th>Last Name</th>
            <th>Middle Name</th>
            <th>First Name</th>
            <th>Reg No</th>
            <th>Department</th>
            <th>level</th>
            <th></th>
        </tr>         
         {%for student in student.items%}
         <tr style="border-bottom: 5px solid rgb(41, 40, 40) ">
            <td>
               <img class="rounded-circle" style="width: 70px; height: 70px;"
                  src="{{url_for('static', filename ='images/' + student.image_name)}}" alt="">
            </td>
            <td>
               {{student.lastname}}
            </td>
            <td>
               {{student.middlename}}
            </td>
            <td>
               {{student.firstname}}
            </td>
            <td>
               {{student.regnumber}}
            </td>
            <td>
               {{student.department.name}}
            </td>
            <td>
               {{student.level}}
            </td>
            <td>
               <form action="{{url_for('portal.registered_students')}}" method="POST">
                  <button type="submit" class="btn btn-primary" name="detail" value="{{student.id}}">View</button>
               </form>
            </td>
         </tr>
         {%endfor%}
      </table>
      {% for page_num in student.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
      {% if student.page == page_num %}
      <a class="btn btn-info mb-4 mt-4" href="{{ url_for('portal.registered_students', page=page_num) }}">{{ page_num }}</a>
      {% else %}
      <a class="btn btn-outline-info mb-4 mt-4" href="{{ url_for('portal.registered_students', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
      {% else %}
      ...
      {% endif %}
      {%endfor%}  
   

{%endblock%}

app/templates/portal/student_details.html
{% extends 'portal.html'%}

{% block page_content %}
<div class="bg-mattBlackLight p-3">
    <h4 class="mb-2">Student Details</h4>
 </div>

 <div class= "container-fluid p-3">
   
    <div class="row">
        {%for student in student%}
        <div class="col-sm-3 mt-4 pt-1">
            <!-- remember to change the filename to correspond to yours  -->
            <img style="max-width: 100%; height: auto; " src="{{url_for('static', filename='images/' + student.image_name)}}" alt="" srcset="">
        </div>

        <div class="col-sm-8 sd p-3" style="height: 400px; border-radius: 5px;">
            <table style="width: 100%;"> 
                <tr>
                    <th><h4>Full Name</h4></th>
                    <td><h4>{{student.lastname}} {{student.middlename}} {{student.firstname}}</h4></td>
                </tr>
                <tr>
                    <th><h4>Registration Number</h4></th>
                    <td><h4>{{student.regnumber}}</h4></td>
                </tr>
                <tr>
                    <th><h4>Department</h4></th>
                    <td><h4>{{student.department.name}}</h4></td>
                </tr>
                <tr>
                    <th><h4>Email</h4></th>
                    <td><h4>{{student.email}}</h4></td>
                </tr>
                <tr>
                    <th><h4>Phone Number</h4></th>
                    <td><h4>{{student.phone}}</h4></td>
                </tr>
                
            </table>
            <button type="button" class="btn btn-primary btn-block" data-target="#courses" data-toggle="modal" >View Registered Courses</button>
            <div class="modal" id="courses">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title"> Registered Courses</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="registered courses">
                            {% for courses in student.course_subscription%}
                                <ul>
                                    <li> {{courses.name}} <br></li>
                                   
                                </ul>
                                      
                            {%endfor%}
                            
                            <form action="{{url_for('portal.edit_courses', student_reg=student.regnumber)}}" method="POST">
                                <button type="submit" class="btn btn-primary btn-block" name="courses" value="{{student.id}}">Edit Courses/Photo </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        {%endfor%}
    </div>
   

 </div>
    


{%endblock page_content%}